services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - totalips
      - emptyips
      - validips
      - badips
      - classifier
      - countryinfo
      - save
      
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - proxy
    networks:
      - default

  totalips:
    build: ./totalips

  emptyips:
    build: ./emptyips

  validips:
    build: ./validips

  badips:
    build: ./badips

  classifier:
    build: ./classifier

  countryinfo:
    build: ./countryinfo

  save:
    build: ./save
